name: CI

on:
  push:
jobs:

       build-and-push:
               runs-on: ubuntu-latest
               steps:
                       - uses: actions/checkout@v4  #clone the code

                       - uses: docker/setup-buildx-actions@v4